using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ShellIcons.Generator;

/// <summary>
/// Emits one <c>{PascalName}.g.cs</c> per SVG icon file passed in via <c>AdditionalFiles</c>,
/// plus a <c>ShellIcon.g.cs</c> dispatcher that looks up icons by kebab-case name.
///
/// Two source packs are supported by convention on file path:
/// <list type="bullet">
///   <item><description>files under <c>catalog/lucide/icons/</c> are tagged <c>lucide</c></description></item>
///   <item><description>files under <c>catalog/custom/icons/</c> are tagged <c>custom</c></description></item>
/// </list>
/// On name collision, custom wins and a <c>SHELLICONS001</c> diagnostic is emitted.
/// </summary>
[Generator]
public sealed class IconGenerator : IIncrementalGenerator
{
    private const string DispatcherNamespace = "ShellIcons";
    private const string IconsNamespace = "ShellIcons.Icons";

    private static readonly DiagnosticDescriptor OverrideDescriptor = new(
        id: "SHELLICONS001",
        title: "Custom icon overrides Lucide icon",
        messageFormat: "Icon '{0}' from catalog/custom/ overrides the Lucide-derived icon of the same name",
        category: "ShellIcons",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var svgs = context.AdditionalTextsProvider
            .Where(t => t.Path.EndsWith(".svg", System.StringComparison.OrdinalIgnoreCase));

        var definitions = svgs
            .Select((text, ct) =>
            {
                var content = text.GetText(ct)?.ToString() ?? string.Empty;
                var kebab = Path.GetFileNameWithoutExtension(text.Path);
                var pascal = Naming.KebabToPascal(kebab);
                var inner = SvgParser.ExtractInner(content);
                var pack = ResolvePack(text.Path);
                return new IconDefinition(kebab, pascal, inner, pack);
            })
            .Where(d => !string.IsNullOrEmpty(d.KebabName) && !string.IsNullOrEmpty(d.InnerMarkup))
            .Collect();

        context.RegisterSourceOutput(definitions, EmitAll);
    }

    private static string ResolvePack(string path)
    {
        var normalized = path.Replace('\\', '/');
        if (normalized.Contains("/catalog/custom/")) return "custom";
        if (normalized.Contains("/catalog/lucide/")) return "lucide";
        return "lucide";
    }

    private static void EmitAll(SourceProductionContext ctx, System.Collections.Immutable.ImmutableArray<IconDefinition> defs)
    {
        var resolved = new Dictionary<string, IconDefinition>();

        foreach (var d in defs)
        {
            if (!resolved.TryGetValue(d.KebabName, out var existing))
            {
                resolved[d.KebabName] = d;
                continue;
            }

            if (d.SourcePack == "custom" && existing.SourcePack != "custom")
            {
                resolved[d.KebabName] = d;
                ctx.ReportDiagnostic(Diagnostic.Create(OverrideDescriptor, Location.None, d.KebabName));
            }
        }

        var ordered = resolved.Values.OrderBy(d => d.KebabName, System.StringComparer.Ordinal).ToArray();

        foreach (var d in ordered)
            ctx.AddSource($"Icons/{d.PascalName}.g.cs", SourceText.From(EmitTypedComponent(d), Encoding.UTF8));

        ctx.AddSource("ShellIcon.g.cs", SourceText.From(EmitDispatcher(ordered), Encoding.UTF8));
    }

    private static string EmitTypedComponent(IconDefinition d)
    {
        var innerLiteral = ToVerbatimStringLiteral(d.InnerMarkup);
        return $$"""
            // <auto-generated/>
            #nullable enable
            using Microsoft.AspNetCore.Components.Rendering;

            namespace {{IconsNamespace}};

            /// <summary>Icon <c>{{d.KebabName}}</c> (source: {{d.SourcePack}}).</summary>
            public sealed class {{d.PascalName}} : global::ShellIcons.IconCore
            {
                /// <inheritdoc />
                protected override string IconName => "{{d.KebabName}}";

                /// <inheritdoc />
                protected override void EmitChildren(RenderTreeBuilder builder, int seq) =>
                    builder.AddMarkupContent(seq, {{innerLiteral}});
            }
            """;
    }

    private static string EmitDispatcher(IconDefinition[] defs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.AspNetCore.Components;");
        sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        sb.AppendLine();
        sb.AppendLine($"namespace {DispatcherNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Dynamic icon dispatcher. Renders any icon in the catalog by kebab-case name:");
        sb.AppendLine("/// <c>&lt;ShellIcon Name=\"chevron-right\" /&gt;</c>.");
        sb.AppendLine("/// <para>");
        sb.AppendLine("/// Trimmer-hostile — referencing this component roots the full catalog. For tree-shakeable");
        sb.AppendLine("/// icons, use the typed form (e.g. <c>&lt;ChevronRight /&gt;</c>).");
        sb.AppendLine("/// </para>");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class ShellIcon : IconCore");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Kebab-case name of the icon to render (e.g. <c>\"chevron-right\"</c>).</summary>");
        sb.AppendLine("    [Parameter] public string Name { get; set; } = string.Empty;");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    protected override string IconName => Name;");
        sb.AppendLine();
        sb.AppendLine("    private static readonly Dictionary<string, string> _catalog = new(StringComparer.Ordinal)");
        sb.AppendLine("    {");
        foreach (var d in defs)
        {
            var lit = ToVerbatimStringLiteral(d.InnerMarkup);
            sb.AppendLine($"        [\"{d.KebabName}\"] = {lit},");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    protected override void EmitChildren(RenderTreeBuilder builder, int seq)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (Name is not null && _catalog.TryGetValue(Name, out var markup))");
        sb.AppendLine("            builder.AddMarkupContent(seq, markup);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Every icon name in the catalog, in sorted order.</summary>");
        sb.AppendLine("    public static IReadOnlyCollection<string> Names => _catalog.Keys;");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToVerbatimStringLiteral(string value)
    {
        var escaped = value.Replace("\"", "\"\"");
        return $"@\"{escaped}\"";
    }
}
